### ISSUE TITLE
Add the ability to upload videos with the webpanel, now that we have mobiclip working.

### ISSUE THREAD

**Issue by Dogmander** [WiiLink24/room-server#16]
This would be a good feature to add

**Comment by 6100m** [comment]
Perhaps music to mov encoding too? Might be a nice feature.

**Comment by spotlightishere** [comment]
This is within #1 primarily, but is something separately that needs to be accomplished.

**Comment by 6100m** [comment]
@spotlightishere Question Spotlight, would it be possible to have it display h265 and surround sound? I mean, it might make the videos have more HQ sound, and with h265 Cacti isn't going to get overloaded on storage.
Also, yay I got to be in the concierge, I'm going to start encoding the videos to show on my mii, so stay tuned for that 😄

**Comment by larsenv** [comment]
> @spotlightishere Question, would it be possible to have it display h265 and surround sound? I mean, it might make the videos have more HQ sound, and with h265 Cacti isn't going to get overloaded on storage.
> Also, yay I got to be in the concierge, I'm going to start encoding the videos to show on my mii, so stay tuned for that 😄

Probably not.

**Comment by spotlightishere** [comment]
The Wii does not support this.

**Comment by spotlightishere** [comment]
Deployed!
