### ISSUE TITLE
Fix category search endpoint

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/room-server#17]
We have categories implemented, but not their retrieval from a search.

```
GET /list/category/search/12345
```

**Comment by 6100m** [comment]
So basically Spotlight, have it retrievable via a custom API we could make?
Akin to queries like this? (not this kind of data specifically, but retreiving recent data in the same manner) https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_get_updated.htm

**Comment by spotlightishere** [comment]
There's a definite response format required by Wii no Ma itself. Not sure how your link comes in to play...

**Comment by spotlightishere** [comment]
The temporary-fix branch resolves this issue. However, beyond this request, `/list/new/all.xml` exists. This must be hardcoded temporarily as well.

**Comment by spotlightishere** [comment]
Resolved.
