### ISSUE TITLE
Can we figure out what's wrong with ratings?

### ISSUE THREAD

**Issue by zurgeg** [WiiLink24/room-server#2]
So my current progress on this is that `nop`ing `80054c50` I get 354116, @spotlightishere What does this error mean?
Anyway, by `nop`ing that address, I effectively removed the if statement on line 23 which says:
```
if (iVar == 0){
    SetNodeMissing(param3,somethingsomethingsomething);
}
```
Which makes me think that we have a missing node. Can anyone take a look at this?

**Comment by 6100m** [comment]
I may look at this later this week with you and Spotlight, also, I made us a new PHP engine (Galvatron) SRC is private atm, read it's README for why.

**Comment by 6100m** [comment]
Actually, it appears to be intentionally missing somehow, odd.

**Comment by 6100m** [comment]
@zurgeg Well, I'll be darned, this is a weird thing Nintendo put in. It's not a missing node, Nintendo is literally setting a missing node ON purpose. Peculiar.

**Comment by 6100m** [comment]
I don't know why they would. @larsenv Does Nintendo do this often? 🤔

**Comment by zurgeg** [comment]
@6100m Interesting, also ratings are working now :)

**Comment by zurgeg** [comment]
I'm gonna close this up as it's fixed. Wii had some invalid images.

**Comment by 6100m** [comment]
Excellent :) I always wondered if those shapes were for ratings, now I know :)

I watched Nintendann's Wii No Ma video repedeatly a month before I joined the Rii No Ma team 😄
