### ISSUE TITLE
Handle poster management from web panel

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/room-server#21]
Now that we have a working listing of movies, we can more easily associate a movie ID. Additionally, we can properly resize uploaded posters to a format acceptable for the Wii.

**Comment by zurgeg** [comment]
In progress as of https://github.com/WiiLink24/room-server/commit/3eb4d9ba4c56c44e2af45b8165dee2b445863fdf

**Comment by SketchMaster2001** [comment]
Added Pay Poster functionality as of 6903f0ca

**Comment by noahpistilli** [comment]
Normal Poster functionality added as of 0762fcf387eeba2c0573103a950c80660f192d9e

**Comment by noahpistilli** [comment]
This should be complete now, all that is left is that image in the back which I don't mind changing manually as it is just one image with no metadata.
