### ISSUE TITLE
Handle Concierge Mii management from web panel

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/room-server#23]
We need to figure out a way to allow Concierge Mii management. This involves defining message types, allowing multiple sorted messages per category, and linking a Mii to a movie.

**Comment by zurgeg** [comment]
Magically done with magic.

**Comment by spotlightishere** [comment]
Partially complete! Going forward we need to allow adding multiple messages per type, and configuring each message's `face`.

For reference:
- 1 is normal
- 2 is a smile
- 3 is worried
- 4 is sad
- 5 is astonished
- 6 is blissful
- 7 is astonished (? slightly different, wider eyes)

Glad to see editing is implemented now! Thank you a ton @zurgeg 🎉
