### ISSUE TITLE
Handle room management from web panel

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/room-server#24]
We currently hardcode all rooms to be the same one. This should be changed.
We need to:
- [x] restructure room code to read from a defined table
- [x] allow movie association for rooms
- [x] have panel functionality to create and destroy rooms

Room offering types must be implemented:
- [x] `smp` (possibly an external website?)
- [x] `enq` (enquete, possibly voting?)
- [x] `mov` (shows a movie)
- [x] `coup` (shows a coupon)
- [x] `link` (opens the Internet Channel)
- [x] `pic` (shows(?) a picture)

**Comment by zurgeg** [comment]
An explanation of what `smp` and `enc` are:
`smp`: Some delivery service thing! You could get stuff delivered to your house, and it would be cash on delivery.
`enq`: Looks like voting to me, if you look at the SEQs, you have ENQUETE_MII_DROP, ENQUETE_VOTE, etc.,

**Comment by 6100m** [comment]
As for pic, that SHOULD be either the poster img data, the movie pic during voting, or a image from concierge. I will fix my PC tonight and look through the decomp on Spotlight's git server to check later tonight.

**Comment by SketchMaster2001** [comment]
enq was completed a while back, should have updated then.

**Comment by SketchMaster2001** [comment]
Room and Parade functionality has been completed as of 3b59c5c
