### ISSUE TITLE
Handle account management from web panel

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/room-server#25]
There is currently no way to create a user beyond manual insertion of a hash. We should allow password reset for users who have been manually inserted.

Additionally, we should most likely investigate permission levels on creation.

**Comment by 6100m** [comment]
If that includes Shop accounts as well, I could do it.

**Comment by spotlightishere** [comment]
These aren't related to shop accounts, and are only related to the panel - thank you though!

**Comment by zurgeg** [comment]
Finished as of https://github.com/WiiLink24/room-server/commit/26c27f878540dcfcbec49c6d61949f64c57a4ed0.
