### ISSUE TITLE
Wii No Ma music on web panel

### ISSUE THREAD

**Issue by 6100m** [WiiLink24/room-server#3]

**Comment by 6100m** [comment]
@zurgeg This would be a cool feature.

**Comment by zurgeg** [comment]
@6100m I agree! Maybe a button to play it? I feel like that would get annoying at some point...

**Comment by 6100m** [comment]
Yeah, that would be best :)

**Comment by 6100m** [comment]
@zurgeg Also status.wiilink24.com changed to status.api.wiilink24.com and yuzu.wiilink24.com changed to yuzu.api.wiilink24.com so be sure to let everyone know that in the discord.

**Comment by 6100m** [comment]
Well, I am going to try to write a youtube-dl downloader for the playlist, to get that initially working. Gimme about 20 mins? :)

**Comment by 6100m** [comment]
Oh no.... youtube-dl actually got taken down, this is bad....

**Comment by 6100m** [comment]
Well, at least their main site is still up. You will have to supply their own binary, but yeah, this is crazy this whole thing happened.

**Comment by 6100m** [comment]
Downloader is pretty much done though.

**Comment by zurgeg** [comment]
> Oh no.... youtube-dl actually got taken down, this is bad....

@6100m the heck? It's perfectly legal...

**Comment by 6100m** [comment]
I know right? It is perfectly legal to archive like that, yeah.

**Comment by 6100m** [comment]
@zurgeg Also in the sulu branch, I left you a downloader for the Wii No Ma OST that hooks into youtube-dl.exe (you must provide your own binary of it) :)

**Comment by 6100m** [comment]
I did make it echo some documentation, and also I did vent in my own code (yes, I do that sometimes lol ;p )

**Comment by 6100m** [comment]
Well, now that the youtube-dl mess is out of the way, it's time I actually do something with this. So it's going to be based off of mympd mainly, and luckily there might just be a chance I can hook that C code into zurgeg's engine. I am thinking of trying to find a python alternative if that is not the case. But yes, this is still be worked on, bear with me here everyone. Also, if anyone who reads this has used mympd in the past, please DM me at 6100m#2193 or DM zurgeg or DM spotlight and please tell us about your experience and your knowledge of the software.

**Comment by spotlightishere** [comment]
I would recommend just using an [audio tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) if at all. Embedding C within the browser sounds quite complicated.

**Comment by 6100m** [comment]
I agree yeah, I can make a shell script to auto download the OST to cacti, will try to get that done today. 🤞

**Comment by larsenv** [comment]
What's the point in playing music on a web panel? It isn't something for general use, it can eventually get annoying, and can take up bandwidth

**Comment by spotlightishere** [comment]
I'm going to close this issue seeing as it's a little overcomplicated for current panel purposes. Perhaps it'll be looked into once more in the future.
