### ISSUE TITLE
Parade image updates silently failing

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/room-server#46]
Parade image updates are silently failing once edited within The Underground. It's unknown why this isn't changing - editing is broken in several others. This issue will hopefully evolve to cover other editing-related errors.

**Comment by SketchMaster2001** [comment]
I am working on Pay Posters tonight, will give it a look

**Comment by SketchMaster2001** [comment]
Fixed in ddffc73

**Comment by SketchMaster2001** [comment]
Pretty much every edit error has been fixed as of my last commit
