### ISSUE TITLE
Handle intro types 

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/room-server#49]
We currently hardcode one intro type. This should eventually be more customizable.
We'll probably want similar with how we do with posters currently DB-wise.

There are a few types that still need investigation before implementation:
- What possible `cnttype`s are there? As it stands from validation, there appears to be `0` (named `UNK` for our purposes) and `1` (referenced as `CAT` within strings).
- What possible `linktype`s are there? There appears to be from 0 to 5, but what do they do?

---

As it stands, we have a very specific arrangement for `introinfo`:
```xml
<introinfo>
  <seq>1</seq>
  <cntid>1</cntid>
  <cnttype>1</cnttype>
  <dispsec>5</dispsec>
  <dimg>1</dimg>
  <random>0</random>
  <linktype>0</linktype>
</introinfo>
```

This is mandated by the validation function for the first sequence. Seeing as type 1 loads an image, it is most likely an image - this needs verification that other things cannot be passed within a second sequence.

Here is a quick list of validation constraints that will hopefully prove to be useful later:
 - If we have a content type of `UNK`, we must have `dispsec` set to true. For `CAT`, we must not have it.
 - Similarly if we have a content type of `UNK`, we must have `dimg` set to true. For `CAT`, we must not have it.
 - If we have a link ID type of 0, we must have a `linkid` specified.
 - If we have a link ID type of 2 or 5, we must have a `catname`. (However, for type 5, the catname is eventually discarded. TODO: figure out why)
 - If we have a type of `UNK` and a `catname`, it must have... something set. TODO: figure out what this something is

TODO: figure out what happens to types such as 1, 3 and 4 as they are not referenced at all by this code.

As follows is an edited version of the validation code that this issue is based off of.
<details>
<summary>Validation code</summary>

```c
int ValidateEventIntroInfo
        (/* unused arguments */ EventIntroInfo *introInfo) {

        if (introInfo->seq == 1) {
                if (introInfo->random == 1) {
                        XMLError(param_2,0x2f);
                        return 0;
                }
                if (introInfo->cnttype != CAT) {
                        XMLError(param_2,0x34);
                        return 0;
                }
                if (introInfo->linktype != TYPE_ZERO) {
                        XMLError(param_2,0x35);
                        return 0;
                }
                if (introInfo->dimg < 1) {
                        XMLError(param_2,0x4c);
                        return 0;
                }
        }

        CNTTypes cnttype = introInfo->cnttype;
        if (((cnttype == UNK) && (introInfo->hasDispsec != false)) ||
            ((cnttype == CAT && (introInfo->hasDispsec == false)))) {
                XMLError(param_2,0x30);
                return 0;
        }

        if (((cnttype == UNK) && (introInfo->hasDimg != false)) ||
            ((cnttype == CAT && (introInfo->hasDimg == false)))) {
                XMLError(param_2,0x31);
                return 0;
        }

        LinkTypes linkType = introInfo->linktype;
        if (((linkType == TYPE_ZERO) && (introInfo->hasLinkId != false)) ||
            ((linkType != TYPE_ZERO && (introInfo->hasLinkId == false)))) {
                XMLError(param_2,0x32);
                return 0;
        }

        bool needsCatname = false;
        if ((linkType == TYPE_TWO) || (linkType == TYPE_FIVE)) {
                needsCatname = true;
        }

        if (needsCatname == introInfo->hasCatname) {
                if ((cnttype == UNK) && (introInfo->hasSomething == false)) {
                        XMLError(param_2,0x3f);
                        return 0;
                } else {
                        if (linkType == TYPE_FIVE) {
                                introInfo->hasCatname = false;
                        }
                        return 1;
                }
        } else {
                XMLError(param_2,0x33);
                return 0;
        }
}
```
</details>

**Comment by zurgeg** [comment]
I would be down to implement with a PR, if I remember correctly I had these types in an XML while experimenting and I believe I also dropped a message in dev chats some time ago @spotlightishere

**Comment by SketchMaster2001** [comment]
Alright, I have found all the link types, how to use them, what they do as well as the cnttypes.

# cnttypes
There are 2 cnttypes

0: A static image. The number per introinfo can be controlled via dime
1: A video in the form of a mobiclip. This must not have dispsec or dimg in the xml. 

# linktypes
As you said, there are 6 link types.

0: Nothing special, just displays the media.
1: Takes you to a theatre category based on the linkid
2: Takes you to watch a movie trailer based on the linkid
3: Takes you to the Shop. This requires a linkid, but doesn't use it
4: Takes you to a room based on the linkid
5: Takes you to a shows category based on the linkid.
