### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by purpelpower** [WiiLink24/room-server#54]
can you use Mysql too or is it limited to
postgresql?

and also if only postgresql works then which version does work?

**Comment by oscie57** [comment]
latest postgres works! its what i use, you may be able to seitch to mysql but i havent tried

**Comment by purpelpower** [comment]
yeah uhm the latest one just didnt work

**Comment by purpelpower** [comment]
also is it possible to host and connect to the v770 branch?

**Comment by SketchMaster2001** [comment]
This is not an issue, please use the discussions tab.

**Comment by SketchMaster2001** [comment]
> latest postgres works! its what i use, you may be able to seitch to mysql but i havent tried

You will have to re-write all the database code
