### ISSUE TITLE
autoincrement at pay categories

### ISSUE THREAD

**Issue by Komfudo** [WiiLink24/room-server#56]
header.xml gives an error at img 0 when a img isn't beginning to 1 or 20000 on pay categories.
i'm not sure about that but snoot tell me that it could be a bug.

**Comment by SketchMaster2001** [comment]
The category ID has to be 5 numbers or the channel errors out. From what I know, we can't really force auto increment to begin at a certain number on creation, but you can run this SQL code to restart auto increment at a specified number.

```sql
ALTER SEQUENCE pay_categories_category_id_seq RESTART WITH 20000
```
