### ISSUE TITLE
Broken Categories

### ISSUE THREAD

**Issue by lambda-makes-things** [WiiLink24/room-server#59]
Categories wont add properly in theunderground. 

If it matters im running this in docker.

@spotlightishere

![Screen Shot 2022-05-04 at 10 31 16 PM](https://user-images.githubusercontent.com/96893300/166868092-01d5f01b-c3bd-46e6-aff1-875bb38cc9f8.png)

**Comment by spotlightishere** [comment]
Thank you for reporting! This should be resolved by f4688123c457dcfdba577a38e465f8975acead5f - please create a new issue if the issue persists.
