### ISSUE TITLE
Investigate pay intro information

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/room-server#60]
(This issue is inspired by 1fe125072d7d6661a50a6d2b16e94ee93a4cf96c.)

For whatever reason, the `linkid` (category ID) specified within a pay intro always falls back to listing the contents of a normal category. We should investigate this behavior, as something else may be going on.

**Comment by SketchMaster2001** [comment]
Looking at our LinkType enum, the `linktype` set in our static dict is the one of a normal category.

```py
class LinkTypes(enum.Enum):
    Regular = 0
    TheatreMovie = 1
    TheatreCategory = 2
    Shop = 3
    Room = 4
    Category = 5
```

**Comment by noahpistilli** [comment]
Scope of the issue has been solved, theatre is more or less complete.
