### ISSUE TITLE
Error on wii no ma launch

### ISSUE THREAD

**Issue by andrjet452** [WiiLink24/room-server#61]
I keep getting error 354163 when launching wii no ma after setting up the server
I uploaded all the necessary content on the admin panel, do you know what the error means?
![image](https://user-images.githubusercontent.com/118829278/203345221-1b5fb4af-2144-498d-a1b7-bc1a60191159.png)
this is everything it downloads from the server, all of them return 200 OK
![image](https://user-images.githubusercontent.com/118829278/203346729-8acd57ff-9df4-4fdb-b28a-8beebc3a3c44.png)

**Comment by noahpistilli** [comment]
This was a bad idea in hindsight pushing the intro info code as I patched the channel to allow for videos. That being said, you cannot have a video as an intro type as I assume you do not have the version which allows for videos. Regardless, the first intro info type must be an image.

**Comment by andrjet452** [comment]
Thanks, I fixed that, but now a different error code shows up, server logs still the same
![image](https://user-images.githubusercontent.com/118829278/203420190-6fe67059-282b-43d6-8a1a-3ff509d7822f.png)

**Comment by andrjet452** [comment]
Can someone please help me with this?
