### ISSUE TITLE
"GET / HTTP/1.1" 404 and "GET /favicon.ico HTTP/1.1" 404 (Flask Localhost Failure + 404)

### ISSUE THREAD

**Issue by WolfTwi97** [WiiLink24/room-server#64]
CMD:

```
* Serving Flask app 'room.py'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:80
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 714-994-209
127.0.0.1 - - [24/Sep/2023 09:42:54] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [24/Sep/2023 09:42:54] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [24/Sep/2023 10:07:32] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [24/Sep/2023 10:42:40] "GET / HTTP/1.1" 404 -
```

When I typed in "localhost" in my browser, the results are:

Not Found The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

This is supposed to be a self hosting for a project I'm doing. The requirements are: Python PostgresSQL

I can't share my db_url though, but from my config Python file, but I have my username, password, localhost, and database.

This development server is supposed to serve for room.py.

I was expecting the localhost to be a success run but failed and I got 404 errors from the CMD.

https://i.stack.imgur.com/YLteT.png

**Comment by noahpistilli** [comment]
You are experiencing 404 because we do not serve a main page nor a favicon file.

If you are looking for the web panel, the path is `/theunderground`.

This issue is invalid, closing.
