### ISSUE TITLE
Permissions system

### ISSUE THREAD

**Issue by oscie57** [WiiLink24/room-server#73]
Currently, the Underground only has one type of user. This allows anyone with access to add users and modify everything on the panel.

A basic permissions system would allow accounts to be made for partners, and for more specific things.

It can go one of two ways:
- Role-like system, where each user has a specific role with permissions
- Value-like system, where every user has a value that grants specific permissions

Some examples of permissions may be:
- Ability to add users
- Ability to add parade rooms
- Ability to upload/modify videos

An example of this system could be that a partner would like to make and manage a room on the service. Instead of having someone else doing it and playing telephone, access could be granted specifically for room creation (and maybe access to only certain rooms could be possible, if the rooms were linked to company roles themselves (for example, Sudomemo role, allowing access to make/modify other rooms under the Sudomemo role))

**Comment by noahpistilli** [comment]
Closed with the introduction of SSO (#77).
